from typing import Final
from interface._constants import WINDOW_HEIGHT, HEADER_HEIGHT


MAX_NEIGHBORS_LABEL: Final[str] = "MAX_NEIGHBORS"
CONSTRUCTION_MAX_CANDIDATES_LABEL: Final[str] = "CONSTRUCTION_MAX_CANDIDATES"
CLASSIFICATION_MAX_CANDIDATES_LABEL: Final[str] = "CLASSIFICATION_MAX_CANDIDATES"
IMAGE_SECTIONS_LABEL: Final[str] = "IMAGE_SECTIONS"
LUMINANCE_THRESHOLD_LABEL: Final[str] = "LUMINANCE_THRESHOLD"
LAYER_GROWTH_FACTOR_LABEL: Final[str] = "LAYER_GROWTH_FACTOR"

LABELS: Final[tuple[str, ...]] = (
    MAX_NEIGHBORS_LABEL,
    CONSTRUCTION_MAX_CANDIDATES_LABEL,
    CLASSIFICATION_MAX_CANDIDATES_LABEL,
    IMAGE_SECTIONS_LABEL,
    LUMINANCE_THRESHOLD_LABEL,
    LAYER_GROWTH_FACTOR_LABEL
)

WELCOME_MESSAGE_WIDTH_RATIO: Final[float] = 0.9
WELCOME_MESSAGE_HEIGHT: Final[int] = 270
WELCOME_MESSAGE_PADDING: Final[tuple[int, int, int, int]] = (0, 0, 0, 20)
WELCOME_MESSAGE_SPACE_BETWEEN: Final[int] = 10
WELCOME_MESSAGE_CORNERS_RADIUS: Final[int] = 15
WELCOME_MESSAGE_FONT_SIZE: Final[int] = 20
WELCOME_MESSAGE_COLOR_LIGHTEN: Final[int] = 5

INPUT_CONTAINER_HEIGHT: Final[int] = 350
INPUT_CONTAINER_COLOR_LIGHTEN: Final[int] = 25
INPUT_CONTAINER_CORNER_RADIUS: Final[int] = 15
INPUT_CONTAINER_SPACE_BETWEEN: Final[int] = 30
INPUT_CONTAINER_FLEX_DIRECTION: Final[str] = "ROW"


INPUT_WIDTH: Final[int] = 300
INPUT_HEIGHT: Final[int] = 50
INPUT_CORNER_RADIUS: Final[int] = 20

LABELED_INPUT_SPACE_BETWEEN: Final[int] = 10
LABELED_INPUT_HORIZONTAL_ALIGNMENT: Final[str] = "CENTER"
LABEL_COLOR: Final[str] = "WHITE"


BODY_COLOR_LIGHTEN: Final[int] = 15
BODY_HEIGHT: Final[int] = WINDOW_HEIGHT - HEADER_HEIGHT
BODY_PADDING: Final[int] = 0
BODY_SPACE_BETWEEN: Final[int] = 30

BUTTON_CONTAINER_SPACE_BETWEEN: Final[int] = 10

BUTTON_WIDTH: Final[int] = 200
BUTTON_HEIGHT: Final[int] = 100

START_BUTTON_COLOR: Final[tuple[int, int, int]] = (120, 208, 98)
START_BUTTON_CORNER_RADIUS: Final[tuple[int, int, int, int]] = (20, 20, 0, 0)
EXIT_BUTTON_COLOR: Final[tuple[int, int, int]] = (227, 8, 66)
EXIT_BUTTON_CORNER_RADIUS: Final[tuple[int, int, int, int]] = (0, 0, 20, 20)
