from typing import Final

from interface._constants import WINDOW_HEIGHT, HEADER_HEIGHT


BODY_COLOR_LIGHTEN: Final[int] = 20
BODY_HEIGHT: Final[int] = WINDOW_HEIGHT - HEADER_HEIGHT
BODY_SPACE_BETWEEN: Final[int] = 20

PROGRESS_CONTAINER_HORIZONTAL_MARGIN: Final[int] = 100
PROGRESS_CONTAINER_HEIGHT: Final[int] = 200
PROGRESS_CONTAINER_SPACE_BETWEEN: Final[int] = 20
PROGRESS_CONTAINER_PADDING: Final[int] = 20
PROGRESS_CONTAINER_HORIZONTAL_ALIGNMENT: Final[str] = "LEFT"
PROGRESS_CONTAINER_CORNER_RADIUS: Final[int] = 20

PROGRESS_BAR_HORIZONTAL_MARGIN: Final[int] = 40
PROGRESS_BAR_HEIGHT: Final[int] = 100
PROGRESS_BAR_CORNER_RADIUS: Final[tuple[int, ...]] = (10, 10, 10, 10)
PROGRESS_BAR_BACKGROUND_CORNER_RADIUS: Final[int] = 10
PROGRESS_BAR_BACKGROUND_DARKEN: Final[int] = 20
PROGRESS_BAAR_HORIZONTAL_ALIGNMENT: Final[str] = "LEFT"

TRAINING_BAR_COLOR: Final[str] = "green"
TESTING_BAR_COLOR: Final[str] = "cyan"

PROGRESS_TEXT_COLOR: Final[str] = "white"
